// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: processer_message.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AbcClient is the client API for Abc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbcClient interface {
}

type abcClient struct {
	cc grpc.ClientConnInterface
}

func NewAbcClient(cc grpc.ClientConnInterface) AbcClient {
	return &abcClient{cc}
}

// AbcServer is the server API for Abc service.
// All implementations must embed UnimplementedAbcServer
// for forward compatibility
type AbcServer interface {
	mustEmbedUnimplementedAbcServer()
}

// UnimplementedAbcServer must be embedded to have forward compatible implementations.
type UnimplementedAbcServer struct {
}

func (UnimplementedAbcServer) mustEmbedUnimplementedAbcServer() {}

// UnsafeAbcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbcServer will
// result in compilation errors.
type UnsafeAbcServer interface {
	mustEmbedUnimplementedAbcServer()
}

func RegisterAbcServer(s grpc.ServiceRegistrar, srv AbcServer) {
	s.RegisterService(&Abc_ServiceDesc, srv)
}

// Abc_ServiceDesc is the grpc.ServiceDesc for Abc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Abc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abc",
	HandlerType: (*AbcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "processer_message.proto",
}
